package:
  name: "fastshermanmorrison-pulsar"
  version: "{{ environ.get('GIT_DESCRIBE_TAG', '0.0.0') }}"

source:
  git_url: https://github.com/vhaasteren/fastshermanmorrison.git
  git_rev: main  # or a specific tag if needed
  git_depth: 1  # shallow clone

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv"

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
    - setuptools_scm
    - numpy
    - cython
  run:
    - python
    - numpy
    - scipy

test:
  imports:
    - fastshermanmorrison

about:
  home: "http://github.com/vhaasteren/fastshermanmorrison/"
  license: "MIT"
  license_file: LICENSE
  summary: "Fast Sherman Morrison calculations for Enterprise"
  dev_url: "http://github.com/vhaasteren/fastshermanmorrison/issues"
