package:
  name: "fastshermanmorrison-pulsar"
  version: "0.4.1"

source:
  path: ..

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv"

requirements:
  host:
    - python
    - pip
    - setuptools
    - numpy >=1.16.3
    - cython >=0.29.32
    - scipy >=1.2.0
    - pytest >=7.4.3
  run:
    - python
    - numpy >=1.16.3
    - scipy >=1.2.0

test:
  imports:
    - fastshermanmorrison

about:
  home: "http://github.com/nanograv/fastshermanmorrison/"
  license: "MIT"
  license_file: LICENSE
  summary: "Fast Sherman Morrison calculations for Enterprise"
  doc_url: "http://github.com/nanograv/fastshermanmorrison/"
  dev_url: "http://github.com/nanograv/fastshermanmorrison/"

extra:
  recipe-maintainers:
    - rutgervanhaasteren
