{% set data = load_setup_py_data() %}

package:
  name: "{{ data.get('name') }}"
  version: "{{ data.get('version') }}"

source:
  path: ..

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv"

requirements:
  host:
    - python
    - pip
    - setuptools
    - numpy
    - cython
    - scipy
  run:
    - python
    - numpy
    - scipy

test:
  imports:
    - fastshermanmorrison

about:
  home: "{{ data.get('url') }}"
  license: "{{ data.get('license') }}"
  summary: "{{ data.get('description') }}"
  doc_url: "{{ data.get('url') }}"
  dev_url: "{{ data.get('url') }}"

extra:
  recipe-maintainers:
    - rutgervanhaasteren
